# ===================================================================
# НАСТРОЙКИ ДЛЯ ОБЫЧНОГО ЗАПУСКА ПРИЛОЖЕНИЯ (ПРОФИЛЬ ПО УМОЛЧАНИЮ)
# ===================================================================
# Основная база данных (H2) - только для чтения транзакций клиентов
spring.datasource.url=jdbc:h2:file:./transaction;MODE=PostgreSQL;ACCESS_MODE_DATA=r
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Вторая база данных (PostgreSQL) - для записи динамических правил
spring.secondary-datasource.url=jdbc:postgresql://localhost:5432/bank_rules
spring.secondary-datasource.driver-class-name=org.postgresql.Driver
spring.secondary-datasource.username=postgres
spring.secondary-datasource.password=0A1n2t3o4n5!

# Настройки JPA / Hibernate - привязываем его конфигурацию к PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
# Указываем url для EntityManager напрямую, чтобы обойти конфликт пулов
spring.jpa.properties.hibernate.connection.url=jdbc:postgresql://localhost:5432/bank_rules
spring.jpa.properties.hibernate.connection.username=postgres
spring.jpa.properties.hibernate.connection.password=0A1n2t3o4n5!