spring.application.name=bank

# --- Первичная БД (H2GIS - Наша старая база - Read Only) ---
spring.datasource.url=jdbc:h2:file:./transaction;ACCESS_MODE_DATA=r
spring.datasource.driver-class-name=org.h2.Driver

# --- Вторичная БД (Направляем в тот же файл сделок, чтобы таблицы создались там) ---
spring.secondary-datasource.url=jdbc:h2:file:./transaction
spring.secondary-datasource.driver-class-name=org.h2.Driver

# Настройки Liquibase для управления схемами во второй БД
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

spring.liquibase.parameters.validate-on-migrate=false
logging.level.org.liquibase=INFO